### ISSUE TITLE
Skewness & kurtosis?

### ISSUE THREAD

**Issue by pmiguelpds** [aeturrell/skimpy#17]
Hey Arthur!
Are you planning to add skewness & kurtosis to the summary stats?
Thanks!
Pedro

**Comment by aeturrell** [comment]
Hey Pedro! Thanks a lot for the suggestion. I've ummed and ahhhed on this one, but ultimately I think it's too much information for the average user (and something that would be easy for the power user to get for themselves). So I think it would be better not to add it in this case.
