### ISSUE TITLE
Bug in string word counts?

### ISSUE THREAD

**Issue by 001ben** [aeturrell/skimpy#296]
https://github.com/aeturrell/skimpy/blob/910eb80cee3e1b69f11cf5555e01995f749aef72/src/skimpy/__init__.py#L414

Noticed some weird behavior with the word counts in skimpy output - should this be using col to subset xf rather than xf.columns[0]?

**Comment by aeturrell** [comment]
It's possible that #386 could solve this too as it's a word count issue. Grateful for a full example of the issue so I can tell, if you can provide one?

**Comment by aeturrell** [comment]
I'm going to close this for now, but will re-open if it's not sorted for you.
