### ISSUE TITLE
Suppress 'sum(cleaned)} column names have been cleaned' Message

### ISSUE THREAD

**Issue by TerryGamon** [aeturrell/skimpy#359]
Could you please add a parameter to allow to supress the 'sum(cleaned)} column names have been cleaned' message?
I would really appreciate it!
Thank you
Regards

**Comment by mcr-is** [comment]
I would like this as well.

**Comment by aeturrell** [comment]
Hi both,

Happy to do this. 

Just interested: is this a preference or interrupting your workflow somehow?

Cheers

**Comment by TerryGamon** [comment]
Hi aeturrell,
thanks for your reply!

Concerning your question:
I wrote functions to collect multiple datasets from a database. Normally the user does this via Jupyter. 
The Database returns dirty column names, which I clean with skimpy. 
(Frankly, I am new to Py, I had all the functions written in R (dplyr) and used janitor::clean_names(), but unfortunately R is dead as a dodo.)
Connection is slow, between every access to the database the program tells the user what it is doing: 
"...Reading this..."
"...Calculating that..."
"...Doing whatever..."

It is not really helpful if it looks like this, the user is not interested in details anyway:

"...Reading this..."

2 column names have been cleaned

"...Calculating that..."

4 column names have been cleaned

"...Doing whatever..."

8 column names have been cleaned


Regards Terry

**Comment by aeturrell** [comment]
I have removed the print out of column name cleaning, in [2fd9bbf](https://github.com/aeturrell/skimpy/commit/2fd9bbf8e1e5727d15e4239506a4223b525912cf)
