### ISSUE TITLE
Inline histogram distorts the output of the layout

### ISSUE THREAD

**Issue by GegznaV** [aeturrell/skimpy#374]
Uneven inline histogram bar widths distort the layout of the output:

![image](https://user-images.githubusercontent.com/12725868/222826663-aabde4be-a2c8-4ac4-b627-7c0663791602.png)

This is the case as UTF-8 symbols (squares) that form the histogram, have different widths.  I noticed that in R, in some cases, 4-th and 8-th (the narrowest) symbols are excluded in some cases:

https://github.com/ropensci/skimr/blob/d5126aa020e703f37740af7ee56a4acb5830fd08/R/stats.R#L133-L136

My question:

- Can an option be added to remove the histogram? Instead, an option to include the median, which is missing, could be added.

**Comment by aeturrell** [comment]
I will take a look at this. Ideally, we would have a solution that didn't use variable widths—it looks like the R code you pointed to avoids this by excluding 4th and 8th? I wonder if there are alternative ways to achieve the same effect.

On replacing with the median, that could be (more) useful to people so I will consider adding that in, either as an option or in general.

**Comment by aeturrell** [comment]
Thinking more about this, it may make sense to just solve the underlying unicode hist problem, while perhaps adding median as an always-included quantile.
