### ISSUE TITLE
Consider Pandas 2.0+ support?

### ISSUE THREAD

**Issue by ianozsvald** [aeturrell/skimpy#451]
Hi there. Pandas 2 came out a few months back and your installation dependency is at `pandas ^1.3.2`. Would you consider checking for Pandas 2 compatibility? 
I'm going to mention `skimpy` on my newsletter (to 1,600 data scientists), I know that a bunch have upgraded to Pandas 2 already (given recent conferences talks I've given on Pandas 2 and Polars), so hopefully that'd open the door to a new base of users for you.
`ydata-profiling` (neé `pandas-profiling`) just added Pandas 2 support too: https://github.com/ydataai/ydata-profiling/releases/tag/v4.3.0
Cheers Ian.

**Comment by aeturrell** [comment]
Hi Ian,

Great to hear from you (I keep meaning to come to one of the London meet ups and say hi!)

Thanks for being interested in skimpy! I will do my best to upgrade it to pandas 2.0 soon—keen to make it as useful as possible for everyone. I don't have an exact timeline but probably a couple of weeks.

**Comment by ianozsvald** [comment]
Very cool - I added it to my newsletter: https://buttondown.email/NotANumber/archive/lessones-learned-at-the-executives-at-pydata/

It would be lovely to say hi - how about giving a lightning talk at a future meetup to 100+ people? https://london.pydata.org/submit-a-talk/
