### ISSUE TITLE
adding support for datetime.date object types

### ISSUE THREAD

**Issue by IgorK7** [aeturrell/skimpy#480]
Hi,

The package is superuseful. However, it seems like the support for some key datatypes frequently used with pandas is missing.
It would be great if you could add support for datetime.date, datetime.month, datetime.year and so on.

for example, it supports datetime64 but if one wants to keep only date part
dt['date'] = dt['datetime'].dt.date

It will give an error "data type 'date' not understood"

Thank you

**Comment by aeturrell** [comment]
Great idea! Will add this to list of features to implement.
