### ISSUE TITLE
Words per row and Word count improper when we have multiple text columns

### ISSUE THREAD

**Issue by akshaytheau** [aeturrell/skimpy#482]
<img width="400" alt="image" src="https://github.com/aeturrell/skimpy/assets/15026338/f0ba26e7-1921-435f-b5dc-07dea340dfe2">

This is the result I got for titanic dataset and it looks improper.

**Comment by akshaytheau** [comment]
<img width="947" alt="image" src="https://github.com/aeturrell/skimpy/assets/15026338/799ee6bb-a333-430a-afe3-787fea7d2361">

**Comment by aeturrell** [comment]
Oh no! This is not good. Will add to list to fix.
