### ISSUE TITLE
Skim output is not able to be recorded or exported to html or svg

### ISSUE THREAD

**Issue by ameresv** [aeturrell/skimpy#529]
I have tried to export skim results. I tried to record it using `Console(record=True)` before calling the function; however, I got a NoneType object. The expected result is an object to be exported via html or svg to share the results obtained. 
I also tested the `Console.capture()` method obtaining the same behavior. Did I do something wrong?

```
from skimpy import skim, generate_test_data
console = Console(record=True)
df = generate_test_data()
skim(df)
console.save_html("demo.html")
```
The demo.html is empty. Thanks for your support
Regards

**Comment by aeturrell** [comment]
Thanks for flagging this. Note that there is a `return_data` option in `skim` too.
