### ISSUE TITLE
Error importing 'Any' from 'typing_extensions' in Databricks environment

### ISSUE THREAD

**Issue by elmerdariovp** [aeturrell/skimpy#695]
Example Description and Error
This script demonstrates how to use the skimpy library to perform a statistical summary of a dataset using Pandas in Python. The dataset used is the "Adult" dataset from the UCI Machine Learning repository, which contains demographic and employment information of adults.

The error occurs when attempting to import the Any class from the typing_extensions module, and is specifically encountered in the Databricks environment. This may be caused by an incompatibility between the Python version and the dependencies of the skimpy library.

Script:
import pandas as pd
from skimpy import skim

# Read data from CSV file
csv_path = "http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
df = pd.read_csv(csv_path, sep=",", header=None)

# Create headers list
headers = ["age","workclass","fnlwgt","education","education-num", "marital-status","occupation",
         "relationship","race","sex", "capital-gain","capital-loss","hours-per-week","native-country","makes"]
df.columns = headers

df.head()

skim(df)

Error on Databricks:
ImportError: cannot import name 'Any' from 'typing_extensions' (/databricks/python/lib/python3.10/site-packages/typing_extensions.py)

How to resolve the ImportError when importing 'Any' from 'typing_extensions' in a Databricks environment?

**Comment by aeturrell** [comment]
I'm afraid this seems to be a problem with Databricks rather than with **skimpy**, and I don't have a Databricks environment to test in to work out what the issue might be. I'm sorry not to be able to help more—best suggestion is to raise it with Databricks directly.
